/* ============================================================
   JLPT_TEST — Bank soal "Tes Kosakata & Tata Bahasa" bergaya
   ujian resmi (format JCT: 語彙 & bunpou pilihan ganda 4 opsi),
   BERBEDA dari mode "Pola Kalimat" yang sudah ada sebelumnya
   (yang berbasis contoh kalimat per pola). Mode ini murni soal
   ujian: cara baca kanji, penulisan kanji, isian kosakata,
   sinonim/makna serupa, dan penggunaan kata yang tepat.
   Sumber: JCT5 (初級≈N5), JCT4 (準中級≈N4), JCT3 (中級≈N3).
   ============================================================ */
const JLPT_TEST = [
/* ============ N5 (JCT5 初級) — 35 soal ============ */
{level:"N5", section:"Cara Baca Kanji", qText:"あちらに <b>電車</b>が とまって いる。", options:["くるま","ふね","でんしゃ","ひこうき"], correctAns:"でんしゃ"},
{level:"N5", section:"Cara Baca Kanji", qText:"<b>年</b>に 一かい 大そうじを する。", options:["ねん","しゅう","たま","つき"], correctAns:"ねん"},
{level:"N5", section:"Cara Baca Kanji", qText:"<b>大人</b>に なったら たくさん りょこうが したい。", options:["だいじん","おおじん","おんな","おとな"], correctAns:"おとな"},
{level:"N5", section:"Cara Baca Kanji", qText:"ここから <b>東</b>に 行くと うみに つく。", options:["ひがし","にし","みなみ","きた"], correctAns:"ひがし"},
{level:"N5", section:"Cara Baca Kanji", qText:"ゲームを かうために お<b>金</b>を ためる。", options:["かね","きん","こん","かな"], correctAns:"かね"},
{level:"N5", section:"Cara Baca Kanji", qText:"わたしの 母は <b>白い</b> ふくが すきだ。", options:["あか","きいろ","あお","しろ"], correctAns:"しろ"},
{level:"N5", section:"Cara Baca Kanji", qText:"これは <b>百年前</b>の おさらだ。", options:["せんねんまえ","ひゃくねんまえ","じゅうねんまえ","いちねんまえ"], correctAns:"ひゃくねんまえ"},
{level:"N5", section:"Cara Baca Kanji", qText:"りんごを <b>一つ</b> ください。", options:["ひとつ","ふたつ","いつつ","ななつ"], correctAns:"ひとつ"},
{level:"N5", section:"Cara Baca Kanji", qText:"いもうとの <b>話</b>は いつも おもしろい。", options:["かれし","いし","はなし","れきし"], correctAns:"はなし"},
{level:"N5", section:"Cara Baca Kanji", qText:"かんじを <b>書く</b>のは むずかしい。", options:["ひく","かく","まく","あく"], correctAns:"かく"},
{level:"N5", section:"Cara Baca Kanji", qText:"今日は <b>天気</b>が いい。", options:["うんき","てんき","きこう","きぶん"], correctAns:"てんき"},
{level:"N5", section:"Cara Baca Kanji", qText:"だれかが <b>来</b>たら おしえて ください。", options:["いたら","したら","みたら","きたら"], correctAns:"きたら"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>なか</b>に 入って まって いて ください。", options:["中","外","間","何"], correctAns:"中"},
{level:"N5", section:"Penulisan Kanji", qText:"カナダは ゆきの おおい <b>くに</b>だ。", options:["日","四","国","円"], correctAns:"国"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>もくようび</b>は 学校が はやく おわる。", options:["土","月","火","木"], correctAns:"木"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>ごご</b>から さんぽに でかけよう。", options:["午前","午後","半前","半後"], correctAns:"午後"},
{level:"N5", section:"Penulisan Kanji", qText:"今日は <b>あめ</b>が ふった。", options:["南","右","水","雨"], correctAns:"雨"},
{level:"N5", section:"Penulisan Kanji", qText:"あたまが いたいから しごとを <b>やすんだ</b>。", options:["休んだ","小んだ","木んだ","本んだ"], correctAns:"休んだ"},
{level:"N5", section:"Penulisan Kanji", qText:"<b>ちょこれーと</b>が だいすきだ。", options:["キョコレート","キョコルート","チョコレート","チョコルート"], correctAns:"チョコレート"},
{level:"N5", section:"Penulisan Kanji", qText:"今日は <b>やま</b>に あそびに 行く。", options:["川","山","三","出"], correctAns:"山"},
{level:"N5", section:"Isian Kosakata", qText:"友だちに（　）を 書きます。", options:["えんぴつ","はなし","がっこう","てがみ"], correctAns:"てがみ"},
{level:"N5", section:"Isian Kosakata", qText:"えいがかんは どこに あるか（　）ますか。", options:["はじまり","わかり","まいり","はいり"], correctAns:"わかり"},
{level:"N5", section:"Isian Kosakata", qText:"（　）すこしで しごとが おわります。", options:["あと","あまり","また","とても"], correctAns:"あと"},
{level:"N5", section:"Isian Kosakata", qText:"ごはんの 前に てを（　）ましょう。", options:["つかい","うたい","ねがい","あらい"], correctAns:"あらい"},
{level:"N5", section:"Isian Kosakata", qText:"やさいを（　）ください。", options:["のって","あって","きって","はしって"], correctAns:"きって"},
{level:"N5", section:"Isian Kosakata", qText:"（　）かばんを かった。", options:["おいしい","あたらしい","いそがしい","すずしい"], correctAns:"あたらしい"},
{level:"N5", section:"Isian Kosakata", qText:"そこは きれいな 川で（　）だ。", options:["ゆうめい","じょうぶ","じょうず","にぎやか"], correctAns:"ゆうめい"},
{level:"N5", section:"Isian Kosakata", qText:"しつもんが ある人は てを（　）。", options:["ひいて","おして","つけて","あげて"], correctAns:"あげて"},
{level:"N5", section:"Isian Kosakata", qText:"あには（　）いそがしそうだ。", options:["いつも","あまり","きっと","だんだん"], correctAns:"いつも"},
{level:"N5", section:"Isian Kosakata", qText:"Ａ「今日は 何が（　）ですか」　Ｂ「パンが いいです」", options:["のみたい","たべたい","すわりたい","ならびたい"], correctAns:"たべたい"},
{level:"N5", section:"Makna Serupa", qText:"もっと 大きい ズボンは ありますか。", options:["あかい ズボンが いいです。","これは 小さいです。","これは かわいくないです。","これは 高いです。"], correctAns:"これは 小さいです。"},
{level:"N5", section:"Makna Serupa", qText:"父は ぎんこうに つとめて いる。", options:["ぎんこうで はたらいている かぞくが いる。","ここは 友だちが はたらく ぎんこうだ。","かぞくと いっしょに ぎんこうに 行く。","この ぎんこうで はたらきたい。"], correctAns:"ぎんこうで はたらいている かぞくが いる。"},
{level:"N5", section:"Makna Serupa", qText:"この 時間は いつも ちょっとだけ おかしを 食べる。", options:["毎日 おかしを たくさん 食べる。","毎日 すこし おかしを 食べる。","ときどき おかしを 食べる。","おかしは からだに わるいから 食べない。"], correctAns:"毎日 すこし おかしを 食べる。"},
{level:"N5", section:"Makna Serupa", qText:"この おみせは 20時までです。", options:["20時前は かいものが できません。","この おみせは 20時に ひらきます。","かいものを するなら 20時に なってからが いいです。","20時になったら この おみせは しまります。"], correctAns:"20時になったら この おみせは しまります。"},
{level:"N5", section:"Makna Serupa", qText:"らいしゅうは もっと さむくなる。", options:["だんだん あたたかくなる。","らいしゅうは ゆきは ふらない。","こんしゅうも さむいが らいしゅうも さむい。","らいしゅうは コートは いらない。"], correctAns:"こんしゅうも さむいが らいしゅうも さむい。"},

/* ============ N4 (JCT4 準中級) — 35 soal ============ */
{level:"N4", section:"Cara Baca Kanji", qText:"私は <b>切手</b>を 集める ことが すきだ。", options:["せっしゅ","きって","きりかた","せつじつ"], correctAns:"きって"},
{level:"N4", section:"Cara Baca Kanji", qText:"私は 毎日 外で <b>運動</b>を している。", options:["どうこう","こうどう","うんどう","うんこう"], correctAns:"うんどう"},
{level:"N4", section:"Cara Baca Kanji", qText:"あなたからは いつも <b>元気</b>を もらっている。", options:["げんき","どうき","じょうき","かんき"], correctAns:"げんき"},
{level:"N4", section:"Cara Baca Kanji", qText:"去年に くらべて 今年は <b>旅行</b>している 人が 多い。", options:["そうこう","しゅぎょう","しぎょう","りょこう"], correctAns:"りょこう"},
{level:"N4", section:"Cara Baca Kanji", qText:"私は 毎日 英語を <b>勉強</b>している。", options:["ざんぎょう","こうちょう","がんじょう","べんきょう"], correctAns:"べんきょう"},
{level:"N4", section:"Cara Baca Kanji", qText:"<b>会社</b>に 行く 用意を する。", options:["ぎょうかい","かいしゃ","こうじょう","けんしょう"], correctAns:"かいしゃ"},
{level:"N4", section:"Cara Baca Kanji", qText:"学校の 授業で <b>作文</b>を 書いた。", options:["しょうもん","ぶんしょう","さくぶん","かくのう"], correctAns:"さくぶん"},
{level:"N4", section:"Cara Baca Kanji", qText:"わたしは 英語を <b>習って</b>います。", options:["はかって","わかって","ならって","しって"], correctAns:"ならって"},
{level:"N4", section:"Cara Baca Kanji", qText:"言葉の <b>意味</b>を 考える。", options:["あじみ","いみ","いけん","みかく"], correctAns:"いみ"},
{level:"N4", section:"Penulisan Kanji", qText:"私は <b>かしゅ</b>に なりたいです。", options:["学習","工業","家主","歌手"], correctAns:"歌手"},
{level:"N4", section:"Penulisan Kanji", qText:"いつまでも <b>がくせい</b>で いたい。", options:["楽生","題生","学生","勉生"], correctAns:"学生"},
{level:"N4", section:"Penulisan Kanji", qText:"母は <b>あかるい</b> 人だ。", options:["赤るい","明るい","安るい","秋るい"], correctAns:"明るい"},
{level:"N4", section:"Penulisan Kanji", qText:"いつか <b>せかい</b>を 旅行したい。", options:["青海","海外","世界","世間"], correctAns:"世界"},
{level:"N4", section:"Penulisan Kanji", qText:"あなたは 私に 本を <b>かして</b>くれた。", options:["貸して","買して","書して","家して"], correctAns:"貸して"},
{level:"N4", section:"Penulisan Kanji", qText:"大きな <b>たてもの</b>の 中に 入る。", options:["立物","建物","立場","質問"], correctAns:"建物"},
{level:"N4", section:"Isian Kosakata", qText:"私は 今から ごはんを（　）。", options:["話す","食べる","聞く","すわる"], correctAns:"食べる"},
{level:"N4", section:"Isian Kosakata", qText:"今日は（　）と 買い物に 行く。", options:["洋服","本","食べ物","友だち"], correctAns:"友だち"},
{level:"N4", section:"Isian Kosakata", qText:"駅で（　）を 待つ。", options:["学校","ゆめ","歌","電車"], correctAns:"電車"},
{level:"N4", section:"Isian Kosakata", qText:"きのうは 風が（　）。", options:["強かった","ふとかった","重かった","安かった"], correctAns:"強かった"},
{level:"N4", section:"Isian Kosakata", qText:"私は 休みの日には（　）を 読む。", options:["空","毎日","映画","本"], correctAns:"本"},
{level:"N4", section:"Isian Kosakata", qText:"母は 絵を かくのが（　）。", options:["とおい","近い","うまい","高い"], correctAns:"うまい"},
{level:"N4", section:"Isian Kosakata", qText:"今日は 天気が（　）から、出かけたい。", options:["多い","よい","おそい","ほそい"], correctAns:"よい"},
{level:"N4", section:"Isian Kosakata", qText:"今から 家に（　）。", options:["歌う","書く","帰る","食べる"], correctAns:"帰る"},
{level:"N4", section:"Isian Kosakata", qText:"あなたは やさしいから 友だちが（　）いる。", options:["たくさん","少し","大きく","小さく"], correctAns:"たくさん"},
{level:"N4", section:"Isian Kosakata", qText:"冬は さむいが、夏は（　）。", options:["長い","おそい","あつい","こわい"], correctAns:"あつい"},
{level:"N4", section:"Makna Serupa", qText:"今日は たくさん 勉強したので もう ねる。", options:["勉強を しないと いけない。","勉強は とても すきだ。","勉強は これからも する。","今日は もう 勉強しない。"], correctAns:"今日は もう 勉強しない。"},
{level:"N4", section:"Makna Serupa", qText:"あの 人の 洋服が かわいい。", options:["あの 人の 洋服が すきでは ない。","あの 人の 洋服が すきだ。","あの 人の 洋服を わたしも 持っている。","あの 人の 洋服は よく ない。"], correctAns:"あの 人の 洋服が すきだ。"},
{level:"N4", section:"Makna Serupa", qText:"図書館で さわいでは いけません。", options:["図書館で うるさくしては いけません。","図書館で さわっては いけません。","図書館で さんぽしては いけません。","図書館で 走っては いけません。"], correctAns:"図書館で うるさくしては いけません。"},
{level:"N4", section:"Makna Serupa", qText:"父は いそいで 家を 出た。", options:["父は 歩いて 家を 出た。","父は いつもと 同じように 家を 出た。","父は すぐに 家を 出た。","父は 何度も 家を 出た。"], correctAns:"父は すぐに 家を 出た。"},
{level:"N4", section:"Makna Serupa", qText:"私は 友だちと いっしょに 学校に 行く。", options:["私は 学校まで 友だちと 歩く。","私は 学校が すきでは ない。","私は 学校に 行っていない。","私は 友だちと 学校が すきだ。"], correctAns:"私は 学校まで 友だちと 歩く。"},
{level:"N4", section:"Penggunaan Kata", qText:"家族", options:["私には ３人の 家族が いる。","家族を 使った おいしい 料理を 作る。","日曜日は いつも 家族に 行っている。","つぎの 休みは 家族を しよう。"], correctAns:"私には ３人の 家族が いる。"},
{level:"N4", section:"Penggunaan Kata", qText:"うれしい", options:["今日の 天気は いつもより うれしいみたいだ。","君の 家の 犬は とても うれしい 犬だね。","友だちに プレゼントを もらって うれしい。","見たことない うれしい 鳥が とんで きた。"], correctAns:"友だちに プレゼントを もらって うれしい。"},
{level:"N4", section:"Penggunaan Kata", qText:"ときどき", options:["今の 時間は ３時 ときどきだ。","私は ときどき ひとりで 歌っている。","見ているだけで 気持ちが ときどき してくる。","あなたは ときどきのように おくれて きますね。"], correctAns:"私は ときどき ひとりで 歌っている。"},
{level:"N4", section:"Penggunaan Kata", qText:"借りる", options:["明日から 新しい 仕事を 借ります。","食べ物を 借りながら 話しては いけません。","あの人は 多くの人に 借りられて います。","あなたの ノートを 借りても よいですか。"], correctAns:"あなたの ノートを 借りても よいですか。"},
{level:"N4", section:"Penggunaan Kata", qText:"ねむい", options:["どうしても ねむいので 少しだけ ねます。","チョコレートは ねむいから 大すきだ。","父が 作る カレーは いつも ねむい。","明日は もっと ねむいことが 起きると 思う。"], correctAns:"どうしても ねむいので 少しだけ ねます。"},

/* ============ N3 (JCT3 中級) — 35 soal ============ */
{level:"N3", section:"Cara Baca Kanji", qText:"試験に向けて教科書の内容を<b>暗記</b>する。", options:["きさい","あんしょう","あんき","きおく"], correctAns:"あんき"},
{level:"N3", section:"Cara Baca Kanji", qText:"今までで一番の<b>困難</b>を迎えている。", options:["こんきゅう","いんすう","いんが","こんなん"], correctAns:"こんなん"},
{level:"N3", section:"Cara Baca Kanji", qText:"少しだけ考える時間が<b>必要</b>だ。", options:["かんよう","ひつよう","ひっす","かんしょう"], correctAns:"ひつよう"},
{level:"N3", section:"Cara Baca Kanji", qText:"人は生まれながらに仕事を自ら選び働く<b>権利</b>をもっている。", options:["しょうき","けんり","そうり","こうき"], correctAns:"けんり"},
{level:"N3", section:"Cara Baca Kanji", qText:"弟は家族の中で一番<b>身長</b>が高い。", options:["せいちょう","しんたい","せたけ","しんちょう"], correctAns:"しんちょう"},
{level:"N3", section:"Cara Baca Kanji", qText:"ケーキを人数に合わせて<b>平等</b>に切り分ける。", options:["びょうどう","へいじょう","こうへい","ひょうてい"], correctAns:"びょうどう"},
{level:"N3", section:"Cara Baca Kanji", qText:"友達から結婚の<b>報告</b>を受ける。", options:["しょうそく","つうしん","ほうこく","こうこく"], correctAns:"ほうこく"},
{level:"N3", section:"Cara Baca Kanji", qText:"<b>祖母</b>は今年で85歳になる。", options:["そぼ","そふ","おじ","おば"], correctAns:"そぼ"},
{level:"N3", section:"Penulisan Kanji", qText:"朝早くから<b>れつ</b>にならんでいます。", options:["例","冷","礼","列"], correctAns:"列"},
{level:"N3", section:"Penulisan Kanji", qText:"この地域も<b>むかし</b>は大勢の人が住んでいた。", options:["現","際","末","昔"], correctAns:"昔"},
{level:"N3", section:"Penulisan Kanji", qText:"勉強に<b>かんけい</b>のないものを学校に持ってこないでください。", options:["関係","間係","関形","間形"], correctAns:"関係"},
{level:"N3", section:"Penulisan Kanji", qText:"ただいまお茶を持って<b>まいります</b>。", options:["満り","参り","回り","末り"], correctAns:"参り"},
{level:"N3", section:"Penulisan Kanji", qText:"かぜのため欠席することを先生に<b>つたえる</b>。", options:["伝える","頼える","続える","違える"], correctAns:"伝える"},
{level:"N3", section:"Penulisan Kanji", qText:"何を<b>こうふく</b>と感じるかは人それぞれだ。", options:["向福","光福","幸福","考福"], correctAns:"幸福"},
{level:"N3", section:"Penulisan Kanji", qText:"新しいドラマの<b>こうせい</b>を考える。", options:["向性","更生","構成","候声"], correctAns:"構成"},
{level:"N3", section:"Penulisan Kanji", qText:"<b>あいする</b>子供のために一生懸命に働く。", options:["想する","愛する","情する","好する"], correctAns:"愛する"},
{level:"N3", section:"Isian Kosakata", qText:"私たちは大学の近くの喫茶店で初めて（　）。", options:["取り上げた","受け取った","出会った","気に入った"], correctAns:"出会った"},
{level:"N3", section:"Isian Kosakata", qText:"睡眠時間が（　）していると疲れがたまりやすくなる。", options:["不足","心配","吸収","左右"], correctAns:"不足"},
{level:"N3", section:"Isian Kosakata", qText:"彼はこの町の（　）場所を知っている。", options:["あらゆる","単なる","いわゆる","どんな"], correctAns:"あらゆる"},
{level:"N3", section:"Isian Kosakata", qText:"転んですぐに、足に（　）痛みを感じた。", options:["明るい","よろしい","上手い","はげしい"], correctAns:"はげしい"},
{level:"N3", section:"Isian Kosakata", qText:"（　）行きたくても、宿題を終えるまでは行ってはいけません。", options:["あまり","どんなに","たしかに","どこも"], correctAns:"どんなに"},
{level:"N3", section:"Isian Kosakata", qText:"この商品はとても人気で（　）手に入らない。", options:["なるべく","なかなか","もしも","なるほど"], correctAns:"なかなか"},
{level:"N3", section:"Isian Kosakata", qText:"あなたの（　）のケーキも冷蔵庫に入っています。", options:["中","わけ","分","もの"], correctAns:"分"},
{level:"N3", section:"Isian Kosakata", qText:"電話の（　）のおかげで、今の便利な生活がある。", options:["発明","許可","学習","記入"], correctAns:"発明"},
{level:"N3", section:"Isian Kosakata", qText:"彼女はいつも（　）研究をしている。", options:["有利に","新鮮に","熱心に","丈夫に"], correctAns:"熱心に"},
{level:"N3", section:"Makna Serupa", qText:"社長が問題を起こしたため、会社の商品の<b>イメージ</b>が悪くなった。", options:["印象","制度","質","評判"], correctAns:"印象"},
{level:"N3", section:"Makna Serupa", qText:"日本に来て１年が経ち、<b>多少</b>日本語を話すことができるようになった。", options:["かなり","容易に","少し","意外に"], correctAns:"少し"},
{level:"N3", section:"Makna Serupa", qText:"仲の悪い二人の意見が、めずらしく<b>一致した</b>。", options:["変わった","協力した","同じだった","けんかした"], correctAns:"同じだった"},
{level:"N3", section:"Makna Serupa", qText:"その日は彼女にとって、<b>一生</b>忘れられない日となった。", options:["しばらくの間","一年間","今までで一番","生きている間"], correctAns:"生きている間"},
{level:"N3", section:"Makna Serupa", qText:"雨は夕方にかけて<b>いっそう</b>強くなるそうだ。", options:["急に","もっと","やはり","いつも通り"], correctAns:"もっと"},
{level:"N3", section:"Penggunaan Kata", qText:"ふと", options:["外がとてもあついので、家の中に入ってふとした。","ふとすると、私も彼と同じ大学に行くかもしれない。","散歩をしていたときに、ふと彼のことを思い出した。","弟の誕生日プレゼントに、ふと漫画を買ってあげた。"], correctAns:"散歩をしていたときに、ふと彼のことを思い出した。"},
{level:"N3", section:"Penggunaan Kata", qText:"じゃま", options:["今は勉強しているので、じゃまをしないでください。","その日はじゃまになるまで、外で友達と遊んでいた。","何かじゃまがあれば、いつでも私にお電話ください。","今日はあついので、じゃまには気をつけてください。"], correctAns:"今は勉強しているので、じゃまをしないでください。"},
{level:"N3", section:"Penggunaan Kata", qText:"悪口", options:["彼女は性格が悪口であるため、友達が少ない。","先生が悪口してくれたおかげで成績が上がった。","私は悪口なので、食べ物の味がよくわからない。","本人がいないところで悪口を言うのはよくない。"], correctAns:"本人がいないところで悪口を言うのはよくない。"},
{level:"N3", section:"Penggunaan Kata", qText:"訓練", options:["火事に備えて訓練をしましょう。","彼は訓練な人なので、人から信頼されている。","この問題は訓練で私には解くことができません。","どんなことも訓練に行えば、上手になります。"], correctAns:"火事に備えて訓練をしましょう。"},
{level:"N3", section:"Penggunaan Kata", qText:"気に入る", options:["あの箱の中には何が入っているのか気に入る。","このかばんは、かるくてかわいいので気に入った。","図書館は静かなので、勉強の内容が気に入る。","今日は朝早くから外出したので、気に入った。"], correctAns:"このかばんは、かるくてかわいいので気に入った。"},
/* ============ N5 — Tata Bahasa (JCT5 D 文法) ============ */
{level:"N5", section:"Tata Bahasa", qText:"わたし（　）お父さんは あたまが いいです。", options:["に","の","が","は"], correctAns:"の"},
{level:"N5", section:"Tata Bahasa", qText:"あさ8時におきて 学校（　）行きます。", options:["に","を","が","と"], correctAns:"に"},
{level:"N5", section:"Tata Bahasa", qText:"ボールペン（　）てがみを書いた。", options:["を","で","に","も"], correctAns:"で"},
{level:"N5", section:"Tata Bahasa", qText:"わたしは いもうと（　）いっしょに かいものに行った。", options:["で","の","が","と"], correctAns:"と"},
{level:"N5", section:"Tata Bahasa", qText:"このどうぶつは いぬでは（　）。", options:["しません","いません","ありません","なりません"], correctAns:"ありません"},
{level:"N5", section:"Tata Bahasa", qText:"えきは（　）から あるいて5分くらいです。", options:["いつ","どれ","その","ここ"], correctAns:"ここ"},
{level:"N5", section:"Tata Bahasa", qText:"（　）ふくが ほしいですか。", options:["どんな","だれに","どこに","なにを"], correctAns:"どんな"},
{level:"N5", section:"Tata Bahasa", qText:"としょかんでは（　）してください。", options:["しずかだ","しずかな","しずかに","しずか"], correctAns:"しずかに"},
{level:"N5", section:"Tata Bahasa", qText:"だんだん（　）なってきた。", options:["くらい","くらく","くらき","くらか"], correctAns:"くらく"},
{level:"N5", section:"Tata Bahasa", qText:"本を（　）前に、このかみに名前を書いてください。", options:["かりる","かりた","かりて","かりない"], correctAns:"かりる"},
{level:"N5", section:"Tata Bahasa", qText:"（　）おかしは すきじゃないです。", options:["あまみ","あまく","あまさ","あまい"], correctAns:"あまい"},
{level:"N5", section:"Tata Bahasa", qText:"さいふをかばんに（　）でかけましょう。", options:["いれよう","いれたら","いれると","いれろ"], correctAns:"いれたら"},
{level:"N5", section:"Tata Bahasa", qText:"（　）できたすいぞくかんに行こう。", options:["ちかくに","ちかくを","ちかくは","ちかくが"], correctAns:"ちかくに"},
{level:"N5", section:"Tata Bahasa", qText:"時間がすこししか（　）。", options:["あります","ありました","ありません","ある"], correctAns:"ありません"},
{level:"N5", section:"Tata Bahasa", qText:"このいえは（　）きれいだ。", options:["いつの","いつが","いつか","いつも"], correctAns:"いつも"},
{level:"N5", section:"Tata Bahasa", qText:"へやにだれ（　）いますか。", options:["は","か","も","に"], correctAns:"か"},
{level:"N5", section:"Susun Kalimat (★)", qText:"これを　＿＿　＿＿　★　＿＿　いいですか。<br><small style='color:var(--sub)'>Susun: たべおわったら／ほかの／りょうりを／たのんで — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["たべおわったら","ほかの","りょうりを","たのんで"], correctAns:"りょうりを"},
{level:"N5", section:"Susun Kalimat (★)", qText:"けさ　＿＿　＿＿　★　＿＿　わすれた。<br><small style='color:var(--sub)'>Susun: でんきを／へやの／わたしは／けし — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["でんきを","へやの","わたしは","けし"], correctAns:"でんきを"},
{level:"N5", section:"Susun Kalimat (★)", qText:"これは　＿＿　＿＿　★　＿＿　です。<br><small style='color:var(--sub)'>Susun: つかう／パスポート／しゃしん／に — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["つかう","パスポート","しゃしん","に"], correctAns:"つかう"},
{level:"N5", section:"Susun Kalimat (★)", qText:"あなたは　＿＿　＿＿　★　＿＿　のですか。<br><small style='color:var(--sub)'>Susun: なろうと／どうして／している／いしゃに — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["なろうと","どうして","している","いしゃに"], correctAns:"なろうと"},
{level:"N5", section:"Susun Kalimat (★)", qText:"この　＿＿　＿＿　★　＿＿　ました。<br><small style='color:var(--sub)'>Susun: わたしと／つくり／ともだちで／おかしは — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["わたしと","つくり","ともだちで","おかしは"], correctAns:"ともだちで"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【１】に入るものは？", options:["つくってください","つくりましょう","つくろう","つくります"], correctAns:"つくります"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【２】に入るものは？", options:["まだ","いつか","あと","もう"], correctAns:"まだ"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Risa):</b><br>わたしは あした あねと ばんごはんを【１】。わたしは【２】一人でりょうりができません。でも、母はしごとでいえにかえるのがいつもおそいので、これからも母が【３】ときは、あねと二人でごはんをつくろうとおもいます。<br><br>【３】に入るものは？", options:["いそがしく","いそがしい","いそがし","いそがしさ"], correctAns:"いそがしい"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Anna):</b><br>おとうとは とても あたまが いいです。毎日たくさんべんきょうをして【４】。わたしはべんきょうがすきではありません。【５】、今日からわたしもおとうとといっしょにべんきょうします。<br><br>【４】に入るものは？", options:["いただきます","いらっしゃい","います","いります"], correctAns:"います"},
{level:"N5", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan (Anna):</b><br>おとうとは とても あたまが いいです。毎日たくさんべんきょうをして【４】。わたしはべんきょうがすきではありません。【５】、今日からわたしもおとうとといっしょにべんきょうします。<br><br>【５】に入るものは？", options:["先に","そして","しかし","では"], correctAns:"しかし"},

/* ============ N4 — Tata Bahasa (JCT4 D 文法) ============ */
{level:"N4", section:"Tata Bahasa", qText:"明日は出発が早いので（　）ようにしましょう。", options:["まちがえない","まちがえず","まちがえて","まちがえた"], correctAns:"まちがえない"},
{level:"N4", section:"Tata Bahasa", qText:"ここからのけしきもすっかりかわって（　）。", options:["しません","しまった","しまいません","しました"], correctAns:"しまった"},
{level:"N4", section:"Tata Bahasa", qText:"このはこには（　）が入っていると思いますか。", options:["どこ","だれ","なぜ","何"], correctAns:"何"},
{level:"N4", section:"Tata Bahasa", qText:"お金が（　）プレゼントを買えたのに。", options:["あれば","あって","あった","ある"], correctAns:"あれば"},
{level:"N4", section:"Tata Bahasa", qText:"私の父は（　）やさしい人だ。", options:["きびしいと","きびしくない","きびしいが","きびしくだが"], correctAns:"きびしいが"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「どうしてアメリカに行こうと思ったのですか」Ｂ「映画を（　）勉強をしたかったんです」", options:["作ら","作ろ","作れ","作る"], correctAns:"作る"},
{level:"N4", section:"Tata Bahasa", qText:"ここではたくさんの（　）魚を見ることができます。", options:["動物に","動物や","動物も","動物で"], correctAns:"動物や"},
{level:"N4", section:"Tata Bahasa", qText:"私は（　）足がはやくない。", options:["兄など","兄だって","兄ほど","兄まで"], correctAns:"兄ほど"},
{level:"N4", section:"Tata Bahasa", qText:"何を買おうとしていたのかぜんぜん（　）。", options:["思い出した","思い出せない","思い出そう","思い出す"], correctAns:"思い出せない"},
{level:"N4", section:"Tata Bahasa", qText:"あのときうそを（　）よかった。", options:["ついた","ついたから","つかなければ","つかない"], correctAns:"つかなければ"},
{level:"N4", section:"Tata Bahasa", qText:"私と姉を（　）ください。", options:["くらべないで","くらべられて","くらべよう","くらべると"], correctAns:"くらべないで"},
{level:"N4", section:"Tata Bahasa", qText:"このイヌに（　）。", options:["さわったり","さわり","さわれば","さわるな"], correctAns:"さわるな"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「かれはじゅぎょう中ねて（　）いるね」Ｂ「つぎのテストがしんぱいだね」", options:["しか","ばかり","いって","きて"], correctAns:"ばかり"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「休みの日は何をしているんですか」Ｂ「テレビを（　）ことが多いです」", options:["みた","みて","みたらしい","みている"], correctAns:"みている"},
{level:"N4", section:"Tata Bahasa", qText:"Ａ「コーヒーを（　）お話ししませんか」Ｂ「いいですね、そうしましょう」", options:["飲みながら","飲もうと","飲めず","飲め"], correctAns:"飲みながら"},
{level:"N4", section:"Susun Kalimat (★)", qText:"しょうらいの　＿＿　＿＿　★　＿＿　ことです。<br><small style='color:var(--sub)'>Susun: 行く／大学に／ゆめは／アメリカの — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["行く","大学に","ゆめは","アメリカの"], correctAns:"大学に"},
{level:"N4", section:"Susun Kalimat (★)", qText:"これからは　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: 物に／食べる／気をつけようと／きめた — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["物に","食べる","気をつけようと","きめた"], correctAns:"気をつけようと"},
{level:"N4", section:"Susun Kalimat (★)", qText:"＿＿　＿＿　★　＿＿　おくれた。<br><small style='color:var(--sub)'>Susun: 止まった／ことで／電車が／会社に — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["止まった","ことで","電車が","会社に"], correctAns:"ことで"},
{level:"N4", section:"Susun Kalimat (★)", qText:"この町には　＿＿　＿＿　★　＿＿　ます。<br><small style='color:var(--sub)'>Susun: あり／ところが／多くの／よい — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["あり","ところが","多くの","よい"], correctAns:"ところが"},
{level:"N4", section:"Susun Kalimat (★)", qText:"つぎの会議　＿＿　＿＿　★　＿＿　そうだ。<br><small style='color:var(--sub)'>Susun: に／は／10日後／開かれる — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["に","は","10日後","開かれる"], correctAns:"に"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【１】に入るものは？", options:["ことに","ことが","ことも","ことの"], correctAns:"ことに"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【２】に入るものは？", options:["さんぽ中と","さんぽ中も","さんぽ中が","さんぽ中の"], correctAns:"さんぽ中の"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【３】に入るものは？", options:["される","された","されば","されず"], correctAns:"される"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【４】に入るものは？", options:["ほど","から","こそ","けど"], correctAns:"から"},
{level:"N4", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>さいきんあまり運動できていないので、家の近くを走る【１】しました。早く起きて走っていると、【２】人があいさつをしてくれます。知らない人にあいさつを【３】とうれしいです。きのうは雨がふっていた【４】走りに行けませんでした。でも、はれた日は毎日【５】と思います。<br><br>【５】に入るものは？", options:["走った","走ったり","走ろう","走るよう"], correctAns:"走ろう"},

/* ============ N3 — Tata Bahasa (JCT3 D 文法) ============ */
{level:"N3", section:"Tata Bahasa", qText:"今日の授業では、環境問題に（　）話し合いましょう。", options:["とって","かけて","ついて","おいて"], correctAns:"ついて"},
{level:"N3", section:"Tata Bahasa", qText:"今回は合格できなかったが、次（　）は絶対に合格したい。", options:["など","こそ","ほど","まで"], correctAns:"こそ"},
{level:"N3", section:"Tata Bahasa", qText:"５年（　）に友人に会ったが、全く変わっていなかった。", options:["きり","だけ","ぶり","さえ"], correctAns:"ぶり"},
{level:"N3", section:"Tata Bahasa", qText:"ここ数年で、平均気温は上がっていく（　）。", options:["一方だ","一回だ","一点だ","一体だ"], correctAns:"一方だ"},
{level:"N3", section:"Tata Bahasa", qText:"この試験に合格するには知識（　）、考える力も必要だ。", options:["だけでも","だけでなく","だけでは","だけなら"], correctAns:"だけでなく"},
{level:"N3", section:"Tata Bahasa", qText:"明日は遠足なので、（　）よいですね。", options:["晴れそう","晴れるかも","晴れるのに","晴れると"], correctAns:"晴れると"},
{level:"N3", section:"Tata Bahasa", qText:"彼女の笑顔は、（　）太陽のように明るい。", options:["まるで","決して","まさか","もしも"], correctAns:"まるで"},
{level:"N3", section:"Tata Bahasa", qText:"Ａ「昨日新しく学校に来た子の名前、なんだ（　）？」Ｂ「田中ゆりさんだよ」", options:["っか","かな","っけ","よね"], correctAns:"っけ"},
{level:"N3", section:"Tata Bahasa", qText:"去年と（　）、今年の夏は雨の日が多い。", options:["比べず","比べて","比べる","比べろ"], correctAns:"比べて"},
{level:"N3", section:"Tata Bahasa", qText:"テレビをつけ（　）、家を出てしまいました。", options:["っぽく","たまま","ながらに","たって"], correctAns:"たまま"},
{level:"N3", section:"Tata Bahasa", qText:"体調が良くなれば、明日は買い物に行く（　）だ。", options:["うち","もの","ところ","つもり"], correctAns:"つもり"},
{level:"N3", section:"Tata Bahasa", qText:"今日中にレポートを終わらせる予定だったが、（　）終わらなかった。", options:["最後","最中","結局","途中"], correctAns:"結局"},
{level:"N3", section:"Tata Bahasa", qText:"Ａ「英語を話せますか？」Ｂ「日常会話（　）なら、話すことができます」", options:["くらい","しか","より","ついで"], correctAns:"くらい"},
{level:"N3", section:"Susun Kalimat (★)", qText:"さっき　＿＿　＿＿　★　＿＿　、明日は学校が休みになるだろう。<br><small style='color:var(--sub)'>Susun: 本当だと／話が／聞いた／すれば — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["本当だと","話が","聞いた","すれば"], correctAns:"本当だと"},
{level:"N3", section:"Susun Kalimat (★)", qText:"私が　＿＿　＿＿　★　＿＿　ください。<br><small style='color:var(--sub)'>Susun: とおりに／折り紙を／説明した／折って — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["とおりに","折り紙を","説明した","折って"], correctAns:"折り紙を"},
{level:"N3", section:"Susun Kalimat (★)", qText:"皆が練習しているのに、　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: 休む／私だけ／いかない／わけには — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["休む","私だけ","いかない","わけには"], correctAns:"わけには"},
{level:"N3", section:"Susun Kalimat (★)", qText:"お菓子を買ってきたので、ここから　＿＿　＿＿　★　＿＿　ください。<br><small style='color:var(--sub)'>Susun: いって／一つずつ／持って／一人 — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["いって","一つずつ","持って","一人"], correctAns:"持って"},
{level:"N3", section:"Susun Kalimat (★)", qText:"実は知っていたが、　＿＿　＿＿　★　＿＿　。<br><small style='color:var(--sub)'>Susun: ふりを／知らない／した／何も — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["ふりを","知らない","した","何も"], correctAns:"ふりを"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>私は最近、運動不足だ。高校生のときまでは体育の授業やクラブ活動【１】があったため、少なくとも１週間に３回ほどは運動をしていた。しかし、大学に入ってからは【２】運動をしなくなってしまったのだ。そこで、私は先月、近所のテニススクールに入った。運動不足だと健康に良くないし、このままだと【３】と思ったからだ。ところが、そこまではげしい運動をしたわけではないのに、先週テニスをしている途中で腰が痛くなってしまった。【４】痛みではなかったので数日で良くなったが、運動不足が原因だと思うと少し悲しくなった。そのため、少しでも運動をしようと思い、今日からは家から駅までの間をバスに【５】に歩くことにした。<br><br>【１】に入るものは？", options:["とも","など","たち","ずつ"], correctAns:"など"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【２】に入るものは？", options:["ふと","いくら","全く","なるべく"], correctAns:"全く"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【３】に入るものは？", options:["太ってくれる","太ってあげる","太ってしまう","太っておこう"], correctAns:"太ってしまう"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【４】に入るものは？", options:["ひどい","かたい","おさない","かしこい"], correctAns:"ひどい"},
{level:"N3", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【５】に入るものは？", options:["乗りぬ","乗らぬ","乗りず","乗らず"], correctAns:"乗らず"},

/* ============ N2 準上級 (JCT2 A) — Kosakata tambahan ============ */
{level:"N2", section:"Cara Baca Kanji", qText:"よい職場を<b>紹介</b>してもらう。", options:["じょうそう","じゅんけい","しゅんこう","しょうかい"], correctAns:"しょうかい"},
{level:"N2", section:"Cara Baca Kanji", qText:"切れ味の<b>鈍い</b>包丁では、トマトがうまく切れない。", options:["おも","おそ","にぶ","かた"], correctAns:"にぶ"},
{level:"N2", section:"Cara Baca Kanji", qText:"部屋の<b>隅</b>でしゃがみこむ。", options:["はし","おき","なか","すみ"], correctAns:"すみ"},
{level:"N2", section:"Cara Baca Kanji", qText:"彼女が欲しがっていたものを<b>贈る</b>。", options:["おく","つく","と","かざ"], correctAns:"おく"},
{level:"N2", section:"Cara Baca Kanji", qText:"彼には以前にも同じ話をしたので、説明を<b>省略</b>する。", options:["せいりょく","しょうりゃく","しゅんらく","しゅうろく"], correctAns:"しょうりゃく"},
{level:"N2", section:"Penulisan Kanji", qText:"首にスカーフを<b>まく</b>。", options:["券","巻","真","包"], correctAns:"巻"},
{level:"N2", section:"Penulisan Kanji", qText:"もったいなくて<b>すてられない</b>。", options:["接","捨","拾","技"], correctAns:"捨"},
{level:"N2", section:"Penulisan Kanji", qText:"地方の<b>のうそん</b>で暮らしている。", options:["濃厚","漁港","豊富","農村"], correctAns:"農村"},
{level:"N2", section:"Penulisan Kanji", qText:"初めて参加した大会で、<b>どう</b>メダルをとった。", options:["銅","鉄","鉱","鋭"], correctAns:"銅"},
{level:"N2", section:"Penulisan Kanji", qText:"ごみを集めたあと、<b>せいそう</b>センターに持っていきました。", options:["高層","正装","清掃","政党"], correctAns:"清掃"},
{level:"N2", section:"Isian Kosakata", qText:"新たに組織の（　）会長となった。", options:["要","副","後","超"], correctAns:"副"},
{level:"N2", section:"Isian Kosakata", qText:"わたしは、りんごを皮（　）食べます。", options:["ごと","ぶり","つき","おき"], correctAns:"ごと"},
{level:"N2", section:"Isian Kosakata", qText:"彼は優れた人間（　）を備えている。", options:["的","化","状","性"], correctAns:"性"},
{level:"N2", section:"Isian Kosakata", qText:"大雨によって、町に深刻な（　）害が出ている。", options:["加","受","被","有"], correctAns:"被"},
{level:"N2", section:"Isian Kosakata", qText:"（　）経験の仕事なので、慣れるまで時間がかかりそうです。", options:["不","非","未","否"], correctAns:"未"},
{level:"N2", section:"Isian Kosakata", qText:"警察によって、関係者以外の立ち入りが（　）されている。", options:["禁止","停止","中止","休止"], correctAns:"禁止"},
{level:"N2", section:"Isian Kosakata", qText:"来月までに10万円を貯金することが（　）です。", options:["目印","目下","目標","目前"], correctAns:"目標"},
{level:"N2", section:"Isian Kosakata", qText:"正確に測らなくても、（　）の長さがそろっていれば大丈夫だよ。", options:["いちいち","だいたい","ときどき","ますます"], correctAns:"だいたい"},
{level:"N2", section:"Isian Kosakata", qText:"忘れ物を取りに帰ったために、学校に（　）してしまった。", options:["延期","延長","遅延","遅刻"], correctAns:"遅刻"},
{level:"N2", section:"Isian Kosakata", qText:"事前に準備をしていたため、仕事が（　）に進んだ。", options:["スムーズ","リズム","オリジナル","メモリー"], correctAns:"スムーズ"},
{level:"N2", section:"Makna Serupa", qText:"困っている人に<b>適切</b>なアドバイスを送る。", options:["適当な","適応な","適用な","適量な"], correctAns:"適当な"},
{level:"N2", section:"Makna Serupa", qText:"ていねいな<b>説明</b>で、数学の問題の内容がよくわかった。", options:["解説","伝説","説得","説教"], correctAns:"解説"},
{level:"N2", section:"Makna Serupa", qText:"<b>やむを得ない</b>事情で会議を欠席する。", options:["内容がわからない","重要ではない","納得できない","仕方ない"], correctAns:"仕方ない"},
{level:"N2", section:"Makna Serupa", qText:"もし書類の内容が間違っていたら、契約を<b>白紙に戻す</b>ことになる。", options:["修正する","新しいものに変える","なかったことにする","同じことをくり返す"], correctAns:"なかったことにする"},
{level:"N2", section:"Makna Serupa", qText:"あの人は<b>クリーンな</b>政治家だと評判だ。", options:["容姿が優れている","悪いことをしない","気が弱く消極的な","長く経験を積んだ"], correctAns:"悪いことをしない"},
{level:"N2", section:"Penggunaan Kata", qText:"上達", options:["彼女はテニスの上達だから、筆記試験を受けずに大学に合格した。","初めての体験でこれだけ上手にできたなら上達だろう。","部長に上達する必要があるので、10時までに資料を用意してください。","毎日くり返し練習したおかげで、ずいぶんと上達した。"], correctAns:"毎日くり返し練習したおかげで、ずいぶんと上達した。"},
{level:"N2", section:"Penggunaan Kata", qText:"合同", options:["正しいと思う意見に合同する。","この映画は、別の映画作品とまったく合同な内容になっている。","これは二人の芸術家が合同で作り上げた作品です。","明後日は駅前で合同しよう。"], correctAns:"これは二人の芸術家が合同で作り上げた作品です。"},
{level:"N2", section:"Penggunaan Kata", qText:"産地", options:["向こうに見える青い屋根の建物が、私の産地です。","今も世界中で、牛が産地されている。","この美味しいメロンの産地はどこですか？","生まれたばかりの赤ちゃんを見て、産地な気分になった。"], correctAns:"この美味しいメロンの産地はどこですか？"},
{level:"N2", section:"Penggunaan Kata", qText:"そっくり", options:["妹の笑った顔が、父親にそっくりだ。","急な仕事が入ってしまい、そっくりする。","うしろの人にもそっくりがよく見えるように向きを変える。","彼はそっくりした性格の人だ。"], correctAns:"妹の笑った顔が、父親にそっくりだ。"},
{level:"N2", section:"Penggunaan Kata", qText:"シンポジウム", options:["文章中にシンポジウムな表現が多く用いられている。","最新の研究に関するシンポジウムが開かれた。","疲れたときには、シンポジウムすることで体を休めるとよい。","先生の教えが、私にとってのシンポジウムとなっている。"], correctAns:"最新の研究に関するシンポジウムが開かれた。"},

/* ============ N2 準上級 — Tata Bahasa (JCT2 A 文法) ============ */
{level:"N2", section:"Tata Bahasa", qText:"もう少しで原稿が完成するので、ぎりぎり（　）待ってもらえませんか。", options:["ほど","のように","まで","から"], correctAns:"まで"},
{level:"N2", section:"Tata Bahasa", qText:"彼は真面目に練習（　）、偉大な選手になっていただろう。", options:["していたら","したので","するから","しようと"], correctAns:"していたら"},
{level:"N2", section:"Tata Bahasa", qText:"次の休みは本を読んだり、絵を（　）過ごそう。", options:["描いて","描くように","描いたりして","描くときに"], correctAns:"描いたりして"},
{level:"N2", section:"Tata Bahasa", qText:"弟のおやつをだれが勝手に食べたのか知って（　）、知らないふりをした。", options:["おこうと","いながら","いようと","いるまいと"], correctAns:"いながら"},
{level:"N2", section:"Tata Bahasa", qText:"何度も確認したのに間違えることなんて、（　）がない。", options:["ありえ","あること","あろうこと","あるはず"], correctAns:"あるはず"},
{level:"N2", section:"Tata Bahasa", qText:"授業の内容については吉田先生に（　）していただきます。", options:["お申し付け","ご話","お申し込み","ご説明"], correctAns:"ご説明"},
{level:"N2", section:"Tata Bahasa", qText:"今日の15時に、先生が私の家に（　）ます。", options:["伺い","いらっしゃい","参り","行かれ"], correctAns:"いらっしゃい"},
{level:"N2", section:"Tata Bahasa", qText:"日も落ちてきたし、もうそろそろ遊びは終わりに（　）。", options:["しよう","ならなければ","した","なっている"], correctAns:"しよう"},
{level:"N2", section:"Tata Bahasa", qText:"合格の連絡がないということは、（　）、不合格ということだ。", options:["それでも","ゆえに","そして","つまり"], correctAns:"つまり"},
{level:"N2", section:"Tata Bahasa", qText:"全国大会に出場（　）、毎日の練習メニューを考える。", options:["するけれども","するために","しようとも","せねば"], correctAns:"するために"},
{level:"N2", section:"Tata Bahasa", qText:"外に出た（　）雨が降り始めた。", options:["とすれば","ところが","とたんに","といえば"], correctAns:"とたんに"},
{level:"N2", section:"Susun Kalimat (★)", qText:"どこでも　＿＿　＿＿　★　＿＿　良いところのひとつだ。<br><small style='color:var(--sub)'>Susun: 飲めるのは／水が／日本の／水道から出る — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["飲めるのは","水が","日本の","水道から出る"], correctAns:"水が"},
{level:"N2", section:"Susun Kalimat (★)", qText:"いつもご飯を　＿＿　＿＿　★　＿＿　食材を食べたい。<br><small style='color:var(--sub)'>Susun: ぜいたくな／たまには／済ますので／安く — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["ぜいたくな","たまには","済ますので","安く"], correctAns:"たまには"},
{level:"N2", section:"Susun Kalimat (★)", qText:"一年の中で　＿＿　＿＿　★　＿＿　よく目を通しておこう。<br><small style='color:var(--sub)'>Susun: 重要な／資料に／会議なので／最も — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["重要な","資料に","会議なので","最も"], correctAns:"会議なので"},
{level:"N2", section:"Susun Kalimat (★)", qText:"＿＿　＿＿　★　＿＿　ことが私の夢です。<br><small style='color:var(--sub)'>Susun: 世界中を／回る／旅に／出て — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["世界中を","回る","旅に","出て"], correctAns:"旅に"},
{level:"N2", section:"Susun Kalimat (★)", qText:"外の　＿＿　＿＿　★　＿＿　着る服を選ぶのがむずかしい。<br><small style='color:var(--sub)'>Susun: 暖かくて／室内は／気温は／低いが — pilih kata yang tepat masuk di posisi ★ (ke-3)</small>", options:["暖かくて","室内は","気温は","低いが"], correctAns:"室内は"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"<b>Bacaan:</b><br>スポーツは、なぜあそこまで人々を感動【１】のだろうか。選手の技術の高さは【２】のこと、チームメートとのコンビネーションプレー、そこから読み取れる選手同士の信頼や友情、選手全員がひとつの目標に全力で向かっていくという熱が、私たちの心を動かす。さらに、実際にプレーをする選手だけではなく、選手を現場でサポートする人々もまた、同じ目標に向かっていく仲間として注目を集めることも少なくない。試合に出てプレーをすることはないにも関わらず、サポートをする人々がテレビで【３】ことも今日では当たり前になっている。【４】、私たちは選手の磨き抜かれた技術よりも、多くの人々が同じ目標を持ち、力を合わせて行動するところにさらなる感動を覚えているのではないのだろうか。私はスポーツを通じて、人間が何よりも【５】な生き物であることを教えられた気分になるのである。<br><br>【１】に入るものは？", options:["ある","する","できる","させる"], correctAns:"させる"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【２】に入るものは？", options:["もちろん","なるほど","なにより","さいわい"], correctAns:"もちろん"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【３】に入るものは？", options:["観る","出演される","放送する","取り上げられる"], correctAns:"取り上げられる"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【４】に入るものは？", options:["なぜなら","おそらく","しかし","または"], correctAns:"しかし"},
{level:"N2", section:"Bunshou (Isi Kosong)", qText:"（同じ文章）【５】に入るものは？", options:["一般的","一時的","社会的","積極的"], correctAns:"社会的"}
];
